name: Update Yearly Weather Data

on:
  workflow_dispatch:
  schedule:
    # run yearly at 1st of January
    - cron: "0 0 1 1 *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install Poetry
        run: |
          pipx install poetry==1.2.0
      - name: Install Dependencies
        run: |
          poetry install
      - name: Run Update Yearly Weather Data
        run: poetry run python update_yearly_weather.py
      - name: Commit and Push
        run: |
          git config --local user.email "robot@koenvangilst.nl"
          git config --local user.name "Robot"
          git add .
          git commit -m "Update yearly weather data"
          git push
